file:
  dir: /Users/jeongseok/Desktop/file_upload_test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinky_brain?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # private yml 파일 포함시켜서 읽어오기
  profiles:
    include: private